-- OpenLab v1.2: automatic cloud snapshot history.
-- The live app still autosaves one current workspace snapshot for fast restore.
-- This table keeps previous snapshots so an accidental overwrite is recoverable.

create table if not exists workspace_snapshot_versions (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references workspaces(id) on delete cascade,
  data jsonb not null,
  saved_at timestamptz not null default now()
);

create index if not exists workspace_snapshot_versions_lookup_idx
on workspace_snapshot_versions(workspace_id, saved_at desc);

alter table workspace_snapshot_versions enable row level security;

create policy "snapshot history read" on workspace_snapshot_versions
for select using (is_workspace_member(workspace_id));

create or replace function archive_workspace_snapshot()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if old.data is distinct from new.data then
    insert into workspace_snapshot_versions(workspace_id, data, saved_at)
    values (old.workspace_id, old.data, now());

    delete from workspace_snapshot_versions
    where id in (
      select id
      from workspace_snapshot_versions
      where workspace_id = old.workspace_id
      order by saved_at desc
      offset 50
    );
  end if;
  return new;
end;
$$;

drop trigger if exists workspace_snapshot_archive on workspace_snapshots;
create trigger workspace_snapshot_archive
before update on workspace_snapshots
for each row execute function archive_workspace_snapshot();
